### ISSUE TITLE
Class not found error

### ISSUE THREAD

**Issue by juampynr** [amosmos/laravel-cli-create-user#10]
I can use the command fine, but then when I open the website I see this error:

![image](https://user-images.githubusercontent.com/108130/32836449-1822fea4-ca0a-11e7-8299-bb439f5f0f5c.png)

**Comment by amosmos** [comment]
Which Laravel version is it? 5.5?

Did you see the package being auto discovered when you installed it with composer?

**Comment by juampynr** [comment]
Doh! I did not read that bit. Thanks. Now it works fine.

**Comment by amosmos** [comment]
Hope you like it :-)
