### ISSUE TITLE
DecryptException

### ISSUE THREAD

**Issue by defji** [amosmos/laravel-cli-create-user#9]
When trying to list users with ```php artisan user:list``` getting this error: 
```
  [Illuminate\Contracts\Encryption\DecryptException]
  The payload is invalid.
```

what should i do?

**Comment by amosmos** [comment]
What version of Laravel is this? Did you upgrade at some point?

**Comment by defji** [comment]
i use latest, 5.5.*

**Comment by amosmos** [comment]
You used it from installation or upgraded to it? The list users command don't have anything to do with Encryption...
